# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-12
# Filename: Q06_iti_namespace.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

# Create the namespace here:
apiVersion: v1  # Specifies the API version
kind: Namespace     # Defines the resource type
metadata:
  name: iti  # Name of the resource
  annotations:
    tracking: "iti_namespace-v1"  # Annotation for tracking purposes

---

# Apply a resource quota to the namespace created up
apiVersion: v1  # Specifies the API version
kind: ResourceQuota  # Defines the resource type
metadata:
  name: my-quota  # Name of the quota resource
  namespace: iti  # Namespace where the quota applies

spec:
  hard:  # Defines the hard limit on resources
    pods: "2"  # Limits the total number of pods in the namespace to 2

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================