# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-12
# Filename: Q15_tolerant_pod.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: v1  # Specifies the API version for Kubernetes apps
kind: Pod     # Defines the resource type
metadata:
  name: tolerant-pod  # Name of the resource type
  annotations:
    tracking: "tolerant-pod-v1"  # Annotation for tracking purposes

spec:  # Pod spec
  tolerations:
    - key: "special-node"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  # Effect of the toleration
  containers:
    - name: nginx-con03  # Name of the container inside the pod
      image: nginx:latest  # Container image used

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================