# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-15
# Filename: Q03_haproxy_clusterrole.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: rbac.authorization.k8s.io/v1 # Specifies the API version for Kubernetes apps
kind: ClusterRole     # Defines the resource type
metadata:
  name: haproxy-cluster-role-devops  # Name of the resource type
  namespace: haproxy-controller-devops # Specifies the namespace for the resource
  annotations:
    tracking: "haproxy-clusterroles-v1"  # Annotation for tracking purposes

rules:
  - apiGroups: ["", "networking.k8s.io", "apiextensions.k8s.io", "discovery.k8s.io"]
    resources: # Resources that HAProxy needs access
      - configmaps
      - secrets
      - endpoints
      - nodes
      - pods
      - services
      - namespaces
      - events
      - serviceaccounts
      - ingresses
      - ingressclasses
      - endpointslices
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================