# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-15
# Filename: Q04_haproxy_clusterbind.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: rbac.authorization.k8s.io/v1 # Specifies the API version for Kubernetes apps
kind: ClusterRoleBinding     # Defines the resource type
metadata:
  name: haproxy-cluster-role-binding-devops  # Name of the resource type
  annotations:
    tracking: "haproxy-clusterbind-v1"  # Annotation for tracking purposes
subjects:
  - kind: ServiceAccount # Specifies the type of subject
    name: haproxy  # Name of the subject
    namespace: haproxy-controller-devops # Specifies the namespace for the resource
    apiGroup: ""  # Specifies the API group for the resource
roleRef:
  kind: ClusterRole # Specifies the type of role
  name: haproxy-cluster-role-devops # Name of the role
  apiGroup: rbac.authorization.k8s.io # Specifies the API group for the role

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================