apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  annotations:
    kubernetes.io/change-cause: "Updated Nginx to version latest"
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-con3
        image: nginx:latest

