# ==============================================
# Created By: Hossam Mahmoud
# Date: 2025-02-10
# Filename: Q06_fluentd_daemon.yml
# Description: Brief description of what the file does
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
# ==============================================

apiVersion: apps/v1  # Specifies the API version for Kubernetes apps
kind: DaemonSet     # Defines the resource type
metadata:
  name: elasticsearch  # Name of the resource type
  labels:
    app: fluentd # Label for the resource type
  annotations:
    tracking: "hosa-fluentd-daemonset-v1"  # Annotation for tracking purposes

spec:
  selector:
    matchLabels:
      app: fluentd  # Selects the pods to be managed by the DaemonSet

  template:  # Defines the pod template for creating replicas
    metadata:
      labels:
        app: fluentd  # Label for the pod

    spec:  # Pod spec
      containers:
        - name: fluentd-daemon-con  # Name of the container inside the pod
          image: k8s.gcr.io/fluentd-elasticsearch:1.20  # Container image used
