# ==============================================
# Created By: Hossam Mahmoud
# Date: 2025-02-10
# Filename: Q09_service_pod.yml
# Description: Brief description of what the file does
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
# ==============================================

apiVersion: v1  # Specifies the API version for Kubernetes apps
kind: Service     # Defines the resource type
metadata:
  name: backend-service  # Name of the resource type
  annotations:
    tracking: "hosa-backend_service-v1"  # Annotation for tracking purposes

spec:  # Pod spec
  type: ClusterIP  # Specifies the service type
  selector:  # Selects the pods to be exposed
    tier: backend  # Selects the pods with the label "tier=backend"
  ports:
  - protocol: TCP # Specifies the protocol for the port
    port: 80  # Port number
    targetPort: 80  # Port number on the container
