# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-12
# Filename: Q11_web_deploy.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: apps/v1  # Specifies the API version for Kubernetes Deployment
kind: Deployment  # Declares the resource type
metadata:
  name: web-app  # Name of the resource
  annotations:
    tracking: "hosa-webapp-deployment-v1"  # Annotation for tracking purposes
  labels:
    app: web-app

spec:
  replicas: 2  # Specifies that 2 replicas (pods) should be created
  selector:
    matchLabels:
      app: web-app  # Ensures the Deployment manages only pods with this label

  template:  # Defines the template for creating pods
    metadata:
      labels:
        app: web-app  # Labels for the pods created by this Deployment

    spec:
      containers:
        - name: nginx-con  # Name of the container inside each pod
          image: nginx:latest  # Specifies the container image to use

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================
