# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-15
# Filename: Q09_pvviewer-role_role.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: rbac.authorization.k8s.io/v1 # Specifies the API version for Kubernetes apps
kind: ClusterRole     # Defines the resource type
metadata:
  name: pvviewer-role  # Name of the resource type
  namespace: default # Specifies the namespace for the resource
  annotations:
    tracking: "pv-clusterroles-v1"  # Annotation for tracking purposes

rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "watch", "list"]

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================