# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-15
# Filename: Q09_pvviewer_svc.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: v1  # Specifies the API version for Kubernetes apps
kind: ServiceAccount     # Defines the resource type
metadata:
  name: pvviewer  # Name of the resource type
  namespace: default # Specifies the namespace for the resource
  annotations:
    tracking: "pv-svacc-v1"  # Annotation for tracking purposes

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================