# ==============================================
#
# ================= FILE START ==================
#
# ==============================================
#
# Created By: Hossam Mahmoud
# Date: 2025-02-13
# Filename: Q09_db-secret_pod.yml
# Description: 
# Version: 1.0.0
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# =========== IMPLEMENTATION START =============
#
# ==============================================

apiVersion: v1  # Specifies the API version for Kubernetes apps
kind: Pod     # Defines the resource type
metadata:
  name: db-pod  # Name of the resource type
  labels:
    app: db  # Label for the resource type
  annotations:
    tracking: "db-pod-v1"  # Annotation for tracking purposes

spec:  # Pod spec
  containers:
    - name: db-mysql-con01  # Name of the container inside the pod
      image: mysql:5.7  # Container image used

      env:
        - name: MYSQL_DATABASE  # Database name
          valueFrom:
            secretKeyRef:
              name: db-secret   # The name of the Kubernetes Secret
              key: MYSQL_DATABASE  # The key inside the Secret

        - name: MYSQL_USER  # Database name
          valueFrom:
            secretKeyRef:
              name: db-secret   # The name of the Kubernetes Secret
              key: MYSQL_USER  # The key inside the Secret

        - name: MYSQL_PASSWORD  # Database name
          valueFrom:
            secretKeyRef:
              name: db-secret   # The name of the Kubernetes Secret
              key: MYSQL_PASSWORD  # The key inside the Secret

        - name: MYSQL_ROOT_PASSWORD  # Database name
          valueFrom:
            secretKeyRef:
              name: db-secret   # The name of the Kubernetes Secret
              key: MYSQL_ROOT_PASSWORD  # The key inside the Secret

# ==============================================
#
# ============ IMPLEMENTATION END ==============
#
# ==============================================
#
# End of File
# Copyright (c) 2025 Hossam. All rights reserved.
#
# ==============================================
#
# ================== FILE END ====================
#
# ==============================================